### ISSUE TITLE
No specified tags/releases

### ISSUE THREAD

**Issue by Mystro256** [Stabyourself/orthorobot#1]
Just a suggestion:

It's usually good practice to tag the new version commits. You can do this straight from Github:

https://github.com/Stabyourself/orthorobot/releases

Click "Draft New Release", Specify Tag Version (such as 1.1) then click on "Target" and there's an option for recent commits.

Typically commits are for any changes, including WIP or experimental changes, and tags are used to specify commits as new release versions of code.

**Comment by Stabyourself** [comment]
I'm thinking of doing a "spring cleaning" type of thing for everything Stabyourself.net once the web version is officially supported.

I'll be updating all the games to that version, change the license of everything to something public-domain-ish, redo the website and properly do everything Git related.

Maybe once all that happens, you can help with any problems I have with Git and Github.

**Comment by Mystro256** [comment]
For sure, I'm down to help out.

**Comment by Mystro256** [comment]
Fixed
